server:
  port: 8081
htrpc:
  registry-center-address: localhost
  registry-center-port: 8848
  registry-center-username: nacos
  registry-center-password: nacos
  registry-center-namespace: public
  service-port: 7777
  service-provider-type: nacos
  request-transport-type: socket
logging:
  level:
    root: info
spring:
  profiles:
    active: kryo
